name: nv
author: Kevin Moore <kevin@thinkpixellab.com>
description: Notational Velocity - Dart
homepage: https://github.com/GoogleChrome/notational_velocity.dart
environment:
  sdk: '>=0.7.6+4'
dependencies:
  bot: '>=0.23.1'
  chrome_gen:
    git: https://github.com/dart-gde/chrome_gen.dart.git
  crypto: '>=0.7.6+4'
  fixnum: '>=0.7.6+4'
  meta: '>=0.7.6+4'
  polymer: '>=0.7.6+4'
dev_dependencies:
  bot_test: '>=0.1.2'
  browser: '>=0.7.6+4'
  hop: '>=0.25.1'
  html5lib: '>=0.7.6+4'
  http_server: '>=0.7.6+4'
  unittest: '>=0.7.6+4'
  webdriver: '>=0.7.5'
