name: nv
author: Kevin Moore <kevin@thinkpixellab.com>
description: Notational Velocity - Dart
homepage: https://github.com/GoogleChrome/notational_velocity.dart
environment:
  sdk: '>=0.7.3+1'
dependencies:
  bot: '>=0.23.0'
  crypto: '>=0.7.3+1'
  fixnum: '>=0.7.3+1'
  js: '>=0.0.24'
  meta: '>=0.7.3+1'
  polymer: '>=0.7.3+1'
dev_dependencies:
  bot_test: '>=0.1.2'
  browser: '>=0.7.3+1'
  hop: '>=0.24.5'
  http_server: '>=0.7.3+1'
  unittest: '>=0.7.3+1'
  webdriver: '>=0.7.5'
