name: nv
description: Notational Velocity - Dart
environment:
  sdk: '>=0.6.15+3'
dependencies:
  bot: any
  js: '>=0.0.24'
  meta: '>=0.6.13'
  polymer: '>=0.5.3'
dev_dependencies:
  bot_test: '>=0.1.2'
  browser: '>=0.6.13'
  hop: '>=0.24.1+1'
  unittest: '>=0.6.13'
