name: nv
author: Kevin Moore <kevin@thinkpixellab.com>
description: Notational Velocity - Dart
homepage: https://github.com/GoogleChrome/notational_velocity.dart
environment:
  sdk: '>=0.6.21'
dependencies:
  bot: '>=0.23.0'
  js: '>=0.0.24'
  meta: '>=0.6.21'
  polymer: '>=0.6.21'
dev_dependencies:
  bot_test: '>=0.1.2'
  browser: '>=0.6.21'
  hop: '>=0.24.3'
  http_server: '>=0.6.21'
  unittest: '>=0.6.21'
  webdriver: '>=0.7.4'
