name: nv
author: Kevin Moore <kevin@thinkpixellab.com>
description: Notational Velocity - Dart
homepage: https://github.com/GoogleChrome/notational_velocity.dart
environment:
  sdk: '>=0.7.5+3'
dependencies:
  bot: '>=0.23.1'
  crypto: '>=0.7.5'
  fixnum: '>=0.7.5'
  js: '>=0.0.24'
  meta: '>=0.7.5'
  polymer: '>=0.7.5'
dev_dependencies:
  bot_test: '>=0.1.2'
  browser: '>=0.7.5'
  hop: '>=0.25.1'
  html5lib: '>=0.7.5'
  http_server: '>=0.7.5'
  unittest: '>=0.7.5'
  webdriver: '>=0.7.5'
